name: Edit Project
description: Edit a GitHub project
author: David Sanders

inputs:
  token:
    description: A GitHub access token - either a classic PAT or a GitHub app installation token
    required: true
  owner:
    description: The owner of the project - either an organization or a user
    required: false
    default: ${{ github.repository_owner }}
  project-number:
    description: The project number from the project's URL
    required: true
  title:
    description: Set the title of the project
    required: false
  description:
    description: Set the short description of the project
    required: false
  readme:
    description: Set the readme description of the project
    required: false
  public:
    description: Set the project to public or private
    required: false

outputs:
  id:
    description: The global ID for the edited project

runs:
  using: node20
  main: ../dist/edit-project.js
